version: "3"

services:
  mysql:
      image: mysql:latest
      container_name: payment-system-mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      volumes:
        - ./docker/database/mysql:/var/lib/mysql
        
  php-fpm:
    container_name: payment-system-php
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./storage/logs:/var/www/logs
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: payment-system-nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    links:
      - php-fpm
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-system-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    depends_on:
      - php-fpm