name: Build and Deploy Main

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_AWS}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{secrets.SSH_USERNAME_AWS}}

          script: |
            cd /var/www/html/
            git pull
            docker-compose restart
            echo 'FINISHED'